# Generated by Django 5.0.3 on 2024-03-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Número da sala')),
                ('status', models.CharField(choices=[('Ocupada', 'Ocupada'), ('Disponível', 'Disponível')], default='Disponível', max_length=10, verbose_name='Status')),
                ('special_room', models.BooleanField(default=False, verbose_name='Sala especial (possui equipamentos)')),
            ],
            options={
                'verbose_name': 'Salas',
                'verbose_name_plural': 'Salas',
            },
        ),
    ]
