# Generated by Django 5.0.3 on 2024-03-18 23:19

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        ('system_constants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do projeto')),
                ('conep_approvement_date', models.DateField(default=datetime.date.today, help_text='Data de aprovação do CONEP (Comitê de Ética em Pesquisa)', verbose_name='Data de Aprovação do CONEP')),
                ('start_date', models.DateField(default=datetime.date.today, help_text='Data de início prevista', verbose_name='Data de Início')),
                ('ending_date', models.DateField(default=datetime.date.today, help_text='Data de término prevista', verbose_name='Data de Término')),
                ('expected_number_of_patients', models.IntegerField(default=1, help_text='Número previsto de pacientes/voluntários no estudo', verbose_name='Número de Pacientes')),
                ('outpatient_care', models.BooleanField(default=False, verbose_name='Atendimento ambulatorial')),
                ('assigned_room', models.ForeignKey(blank=True, help_text='Sala atribuída ao projeto, caso ainda não possua, deixar em branco', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.room', verbose_name='Sala atribuída')),
                ('main_researcher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_researcher', to=settings.AUTH_USER_MODEL, verbose_name='Pesquisador Principal')),
                ('researchers', models.ManyToManyField(related_name='researchers', to=settings.AUTH_USER_MODEL, verbose_name='Pesquisadores')),
            ],
            options={
                'verbose_name': 'Pesquisa',
                'verbose_name_plural': 'Pesquisas',
            },
        ),
        migrations.CreateModel(
            name='ScheduledTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_schedule', to='system_constants.schedule', verbose_name='Horário de Término')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_management.research', verbose_name='Pesquisa')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room', verbose_name='Sala')),
                ('start_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_schedule', to='system_constants.schedule', verbose_name='Horário de Início')),
                ('weekday', models.ManyToManyField(blank=True, to='system_constants.weekdays', verbose_name='Dias da semana')),
            ],
            options={
                'verbose_name': 'Horário marcado',
                'verbose_name_plural': 'Horários marcados',
            },
        ),
    ]
