# Generated by Django 5.0.3 on 2024-03-19 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledtimes',
            options={'verbose_name': 'Pesquisas com horário marcado', 'verbose_name_plural': 'Pesquisas com horários marcados'},
        ),
    ]
