# Generated by Django 5.0.3 on 2024-03-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_management', '0002_alter_scheduledtimes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='research',
            options={'verbose_name': 'Pesquisa cadastrada', 'verbose_name_plural': 'Pesquisas cadastradas'},
        ),
        migrations.AddField(
            model_name='research',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Desmarcar quando um Projeto não apresentar atividade após de 120 dias.', verbose_name='Ativa'),
        ),
        migrations.AlterField(
            model_name='research',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome da pesquisa'),
        ),
    ]
